Switch rollup-http-server to server only implementation

diff --git a/linux/utils/rollup-init b/linux/utils/rollup-init
--- a/linux/utils/rollup-init
+++ b/linux/utils/rollup-init
@@ -11,9 +11,8 @@
 # CONDITIONS OF ANY KIND, either express or implied. See the License for the
 # specific language governing permissions and limitations under the License.
 
-DEFAULT_DAPP_PORT=5003
-DEFAULT_DAPP_TIMEOUT=100
-DEFAULT_HTTP_DISPATCHER_PORT=5004
+DEFAULT_ROLLUP_HTTP_SERVER_TIMEOUT=100
+DEFAULT_ROLLUP_HTTP_SERVER_PORT=5004
 
 usage() {
     echo "Usage:
@@ -25,20 +24,16 @@ where options are:
     --help
         Prints this message.
 
-    --dapp-port <port>
-        Passes to the http-dispatcher the port that the dapp listens to.
-        (default: $DEFAULT_DAPP_PORT)
+    --rollup-http-server-port <port>
+        Passes to the rollup-http-server the port it should listen to.
+        (default: $DEFAULT_ROLLUP_HTTP_SERVER_PORT)
 
-    --http-dispatcher-port <port>
-        Passes to the http-dispatcher the port it should listen to.
-        (default: $DEFAULT_HTTP_DISPATCHER_PORT)
-
-    --dapp-timeout <seconds>
+    --rollup-http-server-timeout <seconds>
         Maximum number of seconds that the dapp should take to start up.
-        (default: $DEFAULT_DAPP_TIMEOUT)
+        (default: $DEFAULT_ROLLUP_HTTP_SERVER_TIMEOUT)
 
-    --http-dispatcher-verbose
-        Enables verbose messages from the http-dispatcher.
+    --rollup-http-server-verbose
+        Enables verbose messages from the rollup-http-server.
         (default: disabled)
 
 and command and arguments:
@@ -63,10 +58,9 @@ check_integer() {
     fi
 }
 
-DAPP_PORT=$DEFAULT_DAPP_PORT
-DAPP_TIMEOUT=$DEFAULT_DAPP_TIMEOUT
-HTTP_DISPATCHER_PORT=$DEFAULT_HTTP_DISPATCHER_PORT
-HTTP_DISPATCHER_VERBOSE=""
+ROLLUP_HTTP_SERVER_TIMEOUT=$DEFAULT_ROLLUP_HTTP_SERVER_TIMEOUT
+ROLLUP_HTTP_SERVER_PORT=$DEFAULT_ROLLUP_HTTP_SERVER_PORT
+ROLLUP_HTTP_SERVER_VERBOSE=""
 
 while [ $# -gt 0 ]
 do
@@ -75,26 +69,20 @@ do
         usage
         exit 0
         ;;
-    --dapp-port)
+    --rollup-http-server-port)
         shift
         check_integer $1
-        DAPP_PORT=$1
+        ROLLUP_HTTP_SERVER_PORT=$1
         shift
         ;;
-    --http-dispatcher-port)
+    --rollup-http-server-timeout)
         shift
         check_integer $1
-        HTTP_DISPATCHER_PORT=$1
+        ROLLUP_HTTP_SERVER_TIMEOUT=$1
         shift
         ;;
-    --dapp-timeout)
-        shift
-        check_integer $1
-        DAPP_TIMEOUT=$1
-        shift
-        ;;
-    --http-dispatcher-verbose)
-        HTTP_DISPATCHER_VERBOSE="--verbose"
+    --rollup-http-server-verbose)
+        ROLLUP_HTTP_SERVER_VERBOSE="--verbose"
         shift
         ;;
     -*)
@@ -107,6 +95,29 @@ do
     esac
 done
 
+# Start http dispatcher
+echo "Starting rollup-http-server: "
+sh -c "rollup-http-server 
+    --address 127.0.0.1:$ROLLUP_HTTP_SERVER_PORT \
+    $ROLLUP_HTTP_SERVER_VERBOSE" &
+
+echo "Rollup http server started"
+
+# Wait for the rollup http server to start up
+RETRY=0
+while ! netstat -ntl 2>&1 | grep $ROLLUP_HTTP_SERVER_PORT > /dev/null
+do
+    echo -n "."
+    sleep 1
+    RETRY=$((RETRY + 1))
+    if [ $RETRY -ge $ROLLUP_HTTP_SERVER_TIMEOUT ]
+    then
+        echo "Error: rollup http server timed out"
+        exit 1
+    fi
+done
+echo ""
+
 # Check if there are any arguments left to start up the dapp
 if [ $# -eq 0 ]
 then
@@ -115,27 +126,10 @@ then
 fi
 
 # Start dapp
-echo -n "Starting dapp: "
-sh -c "$*" &
+echo -n "Starting dapp: " "$*"
+sh -c "$*"
 
-# Wait for the dapp to start up
-RETRY=0
-while ! netstat -ntl 2>&1 | grep $DAPP_PORT > /dev/null
-do
-    echo -n "."
-    sleep 1
-    RETRY=$((RETRY + 1))
-    if [ $RETRY -ge $DAPP_TIMEOUT ]
-    then
-        echo "Error: dapp timed out"
-        exit 1
-    fi
-done
-echo ""
+echo "Result:" $?
 
-# Start http dispatcher
-echo "Starting http-dispatcher: "
-http-dispatcher \
-    --address 127.0.0.1:$HTTP_DISPATCHER_PORT \
-    --dapp 127.0.0.1:$DAPP_PORT \
-    $HTTP_DISPATCHER_VERBOSE
+
+
